### PR TITLE
Fix `autocor`

### LINKED ISSUE #363: autocor errors for short chains
It seems autocor assumes the chains are of length 50 at least. Would be nice to handle short chains as well.

```julia
using Turing

@model function model(data)
  μ ~ Normal(0, 1)
  σ ~ truncated(Cauchy(0, 1), 0, Inf)
  for i in eachindex(data)
    data[i] ~ Normal(μ, σ)
  end
end
data = rand(100)
chain = sample(model(data), NUTS(5, 0.9), MCMCThreads(), 10, 2)
autocor(chain)
```

The error is:
```julia
ERROR: lags must be less than the sample length.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] check_lags
    @ ~/.julia/packages/StatsBase/pJqvO/src/signalcorr.jl:15 [inlined]
  [3] autocor!(r::Vector{Float64}, x::Vector{Float64}, lags::Vector{Int64}; demean::Bool)
    @ StatsBase ~/.julia/packages/StatsBase/pJqvO/src/signalcorr.jl:146
  [4] #autocor#115
    @ ~/.julia/packages/StatsBase/pJqvO/src/signalcorr.jl:196 [inlined]
  [5] #152
    @ ~/.julia/packages/MCMCChains/ECz6m/src/stats.jl:21 [inlined]
  [6] (::MCMCChains.var"#111#118"{MCMCChains.var"#152#153"{Bool, Int64}, Matrix{Float64}})(i::Int64)
    @ MCMCChains ./none:0
  [7] iterate
    @ ./generator.jl:47 [inlined]
  [8] collect(itr::Base.Generator{Base.OneTo{Int64}, MCMCChains.var"#111#118"{MCMCChains.var"#152#153"{Bool, Int64}, Matrix{Float64}}})
    @ Base ./array.jl:724
  [9] #110
    @ ./none:0 [inlined]
 [10] iterate
    @ ./generator.jl:47 [inlined]
 [11] collect_to!
    @ ./array.jl:782 [inlined]
 [12] collect_to_with_first!
    @ ./array.jl:760 [inlined]
 [13] collect(itr::Base.Generator{NTuple{4, MCMCChains.var"#152#153"{Bool, Int64}}, MCMCChains.var"#110#117"{Matrix{Float64}}})
    @ Base ./array.jl:734
 [14] #109
    @ ./none:0 [inlined]
 [15] iterate
    @ ./generator.jl:47 [inlined]
 [16] collect(itr::Base.Generator{Vector{Matrix{Float64}}, MCMCChains.var"#109#116"{NTuple{4, MCMCChains.var"#152#153"{Bool, Int64}}}})
    @ Base ./array.jl:724
 [17] summarize(::Chains{Float64, AxisArrays.AxisArray{Float64, 3, Array{Float64, 3}, Tuple{AxisArrays.Axis{:iter, StepRange{Int64, Int64}}, AxisArrays.Axis{:var, Vector{Symbol}}, AxisArrays.Axis{:chain, UnitRange{Int64}}}}, Missing, NamedTuple{(:parameters, :internals), Tuple{Vector{Symbol}, Vector{Symbol}}}, NamedTuple{(:start_time, :stop_time), Tuple{Vector{Float64}, Vector{Float64}}}}, ::Function, ::Vararg{Function}; sections::Symbol, func_names::Vector{Symbol}, append_chains::Bool, name::String, additional_df::Nothing)
    @ MCMCChains ~/.julia/packages/MCMCChains/ECz6m/src/summarize.jl:174
 [18] autocor(chains::Chains{Float64, AxisArrays.AxisArray{Float64, 3, Array{Float64, 3}, Tuple{AxisArrays.Axis{:iter, StepRange{Int64, Int64}}, AxisArrays.Axis{:var, Vector{Symbol}}, AxisArrays.Axis{:chain, UnitRange{Int64}}}}, Missing, NamedTuple{(:parameters, :internals), Tuple{Vector{Symbol}, Vector{Symbol}}}, NamedTuple{(:start_time, :stop_time), Tuple{Vector{Float64}, Vector{Float64}}}}; lags::Vector{Int64}, demean::Bool, append_chains::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ MCMCChains ~/.julia/packages/MCMCChains/ECz6m/src/stats.jl:24
 [19] autocor(chains::Chains{Float64, AxisArrays.AxisArray{Float64, 3, Array{Float64, 3}, Tuple{AxisArrays.Axis{:iter, StepRange{Int64, Int64}}, AxisArrays.Axis{:var, Vector{Symbol}}, AxisArrays.Axis{:chain, UnitRange{Int64}}}}, Missing, NamedTuple{(:parameters, :internals), Tuple{Vector{Symbol}, Vector{Symbol}}}, NamedTuple{(:start_time, :stop_time), Tuple{Vector{Float64}, Vector{Float64}}}})
    @ MCMCChains ~/.julia/packages/MCMCChains/ECz6m/src/stats.jl:18
 [20] top-level scope
    @ REPL[7]:1
```

### PR DESCRIPTION
**Pull request by devmotion**
Fixes #363.

### CODE REVIEW

File: src/stats.jl [hunk 1]
```diff
@@ -1,18 +1,25 @@
...
-Setting `append_chains=false` will return a vector of dataframes containing the
-autocorrelations for each chain.
+The default `lags` are `[1, 5, 10, 50]`, upper-bounded by `n - 1` where `n` is the number of samples used in the estimation.
+
+Setting `append_chains=false` will return a vector of dataframes containing the autocorrelations for each chain.
 """
 function autocor(
     chains::Chains;
-    lags::AbstractVector{<:Integer} = [1, 5, 10, 50],
+    append_chains = true,
```
Comment (devmotion) [inline src/stats.jl:20]: This was inconsistent with all other functions. Therefore also the tests didn't seem reasonable since they only tested `append_chains=false`.

**Review by yebai — APPROVED** [review]
thanks, @devmotion - it looks good to me!

**Comment by devmotion** [comment]
Don't merge, I just noticed that the autocor plots have to be updated to account for `append_chains=true` defaults.

**Comment by devmotion** [comment]
OK, it's fixed now (https://beta.turing.ml/MCMCChains.jl/previews/PR364/statsplots/#Autocorrelation).
